# Generated by Django 4.2.4 on 2023-08-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
                ('gender', models.TextField(blank=True, max_length=10, null=True)),
                ('religion', models.CharField(choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddhoism', 'Buddhoism'), ('Others', 'Others')], max_length=25)),
                ('phone_number', models.TextField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.TextField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
