# Generated by Django 4.2.4 on 2023-08-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0005_profile_degree_profile_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
