# Generated by Django 4.2.4 on 2023-08-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0006_profile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
